version: "3.8"

services:
    backend:
        build:
            context: ./backend
        ports:
            - "3001:3001"
        restart: always
        container_name: exchange-now-back

    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:80"
        restart: always
        container_name: exchange-now-front
        depends_on:
            - backend
